version: '3'

services:
  validator:
    container_name: validator
    image: ghcr.io/celestiaorg/celestia-app:v0.13.2
    environment:
      - VALIDATOR_NAME=validator
      - KEY_NAME=validator
      - CHAIN_ID=sov-testnet
      - CELES_AMOUNT=12000000000000000000000000utia
      - STAKING_AMOUNT=1000000000utia
    ports:
      - "9090:9090"
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
    entrypoint:
      - /bin/sh
      - -c
      - |
        /bin/celestia-appd init $$VALIDATOR_NAME --chain-id $$CHAIN_ID && \
        /bin/celestia-appd keys add $$VALIDATOR_NAME --keyring-backend test && \
        /bin/celestia-appd add-genesis-account $$VALIDATOR_NAME $$CELES_AMOUNT --keyring-backend test && \
        /bin/celestia-appd gentx "$$VALIDATOR_NAME" "$$STAKING_AMOUNT" --chain-id $$CHAIN_ID --keyring-backend test --evm-address 0x1aD2B053b8c6b1592cB645DEfadf105F34d8C6e1 && \
        /bin/celestia-appd collect-gentxs && \
        /bin/celestia-appd tendermint show-node-id && \
        /bin/celestia-appd start
    volumes:
      - ./keyring-test:/root/.celestia-app/keyring-test/

  bridge:
    image: ghcr.io/celestiaorg/celestia-node:v0.7.1
    environment:
      - KEY_NAME=validator
      - CHAIN_ID=sov-testnet
      - STAKING_AMOUNT=1000000000utia
    depends_on:
      - validator
    entrypoint:
      - /bin/sh
      - -c
      - |
        /celestia bridge init --node.store /bridge --p2p.network $$CHAIN_ID && \
        cp -r /root/keyring-test /root/.celestia-light-mocha/keys/keyring-test
        /celestia bridge start --node.store /bridge --gateway --core.ip validator --keyring.accname $$KEY_NAME --p2p.network $$CHAIN_ID
    volumes:
      - ./keyring-test:/root/keyring-test/
