start_height = 670316
[da]
celestia_rpc_auth_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJBbGxvdyI6WyJwdWJsaWMiLCJyZWFkIiwid3JpdGUiLCJhZG1pbiJdfQ.cLBCsC0k0HKBCJwTLNRmlmsMe1xuZ00MbKz0HpFcXuk"
celestia_rpc_address = "http://localhost:11111/"
# 100 MB
max_celestia_response_body_size = 104_857_600
[runner.storage]
path = "demo_data"
[rpc_config]
bind_host = "127.0.0.1"
bind_port = 12345

